import type { Incident, RcaResult } from "@/lib/types";

/**
 * In-memory fixtures recreating the three incidents from the mockup.
 * INC-7 reproduces the design verbatim; INC-6 / INC-5 are plausible resolved
 * incidents so every list filter and view has complete data.
 *
 * `firstSeen` timestamps use fixed UTC clock values so the investigation header
 * renders stable "HH:MM UTC" labels matching the mockup. `updatedAt` uses
 * offsets from load time so the sidebar's relative-time labels stay fresh
 * ("4m ago", "2d ago", "3d ago").
 */

const now = Date.now();
const minutesAgo = (m: number): string => new Date(now - m * 60_000).toISOString();
const daysAgo = (d: number): string => new Date(now - d * 86_400_000).toISOString();

// ---------------------------------------------------------------------------
// INC-7 — TypeError in checkout flow (live / investigating) — verbatim mockup
// ---------------------------------------------------------------------------

const INC7_POSTMORTEM_MD = `# INC-7 — Checkout failures for guest users after user-lookup refactor

**Service:** checkout-api · **Severity:** sev-2 · **Confidence:** 92% · **Date:** 2026-07-15

_Generated by Responder · reviewed by human._

## Summary

For 24 minutes, every guest checkout on \`POST /checkout\` returned a 500. A refactor deployed at 13:58 UTC removed the null guard in \`findUser()\`, so requests without an existing user record dereferenced \`user.email\` on undefined. 14 requests failed before the fix PR was opened.

## Timeline (UTC)

- **13:58** — Deploy d-482 ships commit \`a3f9c12\` ("refactor: simplify user lookup")
- **14:02** — First TypeError on /checkout; errors recur on every guest request
- **14:06** — Exception filter fires webhook → Responder opens INC-7, agent starts
- **14:07** — Agent correlates deploy timing, logs, diff; submits RCA (7 steps, 48s)
- **14:22** — Fix PR #214 opened; incident marked resolved after merge + deploy

## Root Cause

Commit \`a3f9c12\` deleted the \`if (!user) throw NotFoundException\` branch from \`users.service.ts\`. Line 42 then reads \`user.email\` unconditionally.

\`\`\`diff
// users.service.ts — a3f9c12
- if (!user) {
-   throw new NotFoundException();
- }
  return user.email;   // line 42 — throws for guests
\`\`\`

## Evidence

1. Zero matching errors in logs before 14:02; deploy landed 13:58 — 4-minute correlation window
2. All 14 stack traces terminate at \`users.service.ts:42\`, the exact line touched by the diff
3. Failing requests all lack a \`userId\` — consistent with the removed guest-user guard

## Fix

PR #214 — fix: restore null guard in findUser() — **merged**

\`\`\`diff
@@ users.service.ts:40 @@
+ if (!user) {
+   throw new NotFoundException();
+ }
  return user.email;
\`\`\`

## Action Items

- [ ] Add integration test covering guest checkout path — owner: TBD
- [ ] Lint rule: forbid removing null guards without replacement — owner: TBD
`;

const INC7_RCA: RcaResult = {
  rootCause: "Null guard removed from findUser() in commit a3f9c12",
  confidence: 0.92,
  suspectCommit: "a3f9c12",
  evidence: [
    "Zero matching errors in logs before 14:02; deploy landed 13:58 — 4-minute correlation window",
    "All 14 stack traces terminate at users.service.ts:42, the exact line touched by the diff",
    "Failing requests all lack a userId — consistent with the removed guest-user guard",
  ],
  proposedPatch: `@@ users.service.ts:40 @@
+ if (!user) {
+   throw new NotFoundException();
+ }
  return user.email;`,
  postmortemMd: INC7_POSTMORTEM_MD,
  service: "checkout-api",
  severity: "sev-2",
  prNumber: 214,
  prUrl: "https://github.com/demo-app/checkout-api/pull/214",
  prMerged: true,
  title: "Checkout failures for guest users after user-lookup refactor",
  summary:
    "For 24 minutes, every guest checkout on `POST /checkout` returned a 500. A refactor deployed at 13:58 UTC removed the null guard in `findUser()`, so requests without an existing user record dereferenced `user.email` on undefined. 14 requests failed before the fix PR was opened.",
  rootCauseSnippet: `// users.service.ts — a3f9c12
- if (!user) {
-   throw new NotFoundException();
- }
  return user.email;   // line 42 — throws for guests`,
  fixDescription: "fix: restore null guard in findUser() — merged",
  date: "2026-07-15",
  timeline: [
    { time: "13:58", text: 'Deploy d-482 ships commit `a3f9c12` ("refactor: simplify user lookup")', tone: "muted" },
    { time: "14:02", text: "First TypeError on /checkout; errors recur on every guest request", tone: "danger" },
    { time: "14:06", text: "Exception filter fires webhook → Responder opens INC-7, agent starts", tone: "muted" },
    { time: "14:07", text: "Agent correlates deploy timing, logs, diff; submits RCA (7 steps, 48s)", tone: "muted" },
    { time: "14:22", text: "Fix PR #214 opened; incident marked resolved after merge + deploy", tone: "success" },
  ],
  actionItems: [
    { text: "Add integration test covering guest checkout path", owner: "TBD" },
    { text: "Lint rule: forbid removing null guards without replacement", owner: "TBD" },
  ],
  // [DISPLAY] Condensed evidence bullets shown in the compact RCA card.
  evidenceBrief: [
    "Deploy d-482 shipped a3f9c12 at 13:58; errors began 14:02",
    "Diff deleted the `if (!user)` branch in users.service.ts",
    "All 14 stack traces terminate at users.service.ts:42",
  ],
};

// ---------------------------------------------------------------------------
// INC-6 — Orders query timeout (resolved)
// ---------------------------------------------------------------------------

const INC6_POSTMORTEM_MD = `# INC-6 — Orders list timeouts after search migration

**Service:** orders-svc · **Severity:** sev-3 · **Confidence:** 88% · **Date:** 2026-07-13

_Generated by Responder · reviewed by human._

## Summary

\`GET /orders\` began timing out for accounts with large order histories after a migration dropped the composite index backing the default sort. Queries fell back to a full table scan and exceeded the 5s statement timeout.

## Timeline (UTC)

- **09:10** — Migration m-118 drops \`idx_orders_customer_created\`
- **09:41** — First query timeout; error rate climbs to 92 over 2 hours
- **09:52** — Responder opens INC-6, agent correlates migration + slow-query log
- **10:20** — Fix PR #207 opened to recreate the index concurrently

## Root Cause

Migration \`m-118\` removed \`idx_orders_customer_created\` as part of a cleanup. The default \`/orders\` sort (\`customer_id, created_at DESC\`) then had no supporting index.

## Evidence

1. Slow-query log shows sequential scans on \`orders\` starting exactly at 09:41
2. 92 timeouts all share \`ORDER BY created_at DESC\` with a high row count
3. Query plan reverts to \`Index Scan\` once the index is restored

## Fix

PR #207 — perf: recreate idx_orders_customer_created concurrently — **merged**

## Action Items

- [ ] Add a guard preventing index drops without a replacement plan — owner: TBD
- [ ] Alert on p95 query latency for /orders — owner: TBD
`;

const INC6_RCA: RcaResult = {
  rootCause: "Composite index idx_orders_customer_created dropped by migration m-118",
  confidence: 0.88,
  suspectCommit: "m-118",
  evidence: [
    "Slow-query log shows sequential scans on orders starting exactly at 09:41",
    "92 timeouts all share ORDER BY created_at DESC with a high row count",
    "Query plan reverts to Index Scan once the index is restored",
  ],
  proposedPatch: `@@ migrations/m-119.sql @@
+ CREATE INDEX CONCURRENTLY idx_orders_customer_created
+   ON orders (customer_id, created_at DESC);`,
  postmortemMd: INC6_POSTMORTEM_MD,
  service: "orders-svc",
  severity: "sev-3",
  prNumber: 207,
  prUrl: "https://github.com/demo-app/orders-svc/pull/207",
  prMerged: true,
  title: "Orders list timeouts after search migration",
  summary:
    "`GET /orders` began timing out for accounts with large order histories after a migration dropped the composite index backing the default sort. Queries fell back to a full table scan and exceeded the 5s statement timeout.",
  rootCauseSnippet: `-- m-118 (cleanup)
- DROP INDEX idx_orders_customer_created;
  -- default sort now unindexed → seq scan`,
  fixDescription: "perf: recreate idx_orders_customer_created concurrently — merged",
  date: "2026-07-13",
  timeline: [
    { time: "09:10", text: "Migration m-118 drops `idx_orders_customer_created`", tone: "muted" },
    { time: "09:41", text: "First query timeout; error rate climbs to 92 over 2 hours", tone: "danger" },
    { time: "09:52", text: "Responder opens INC-6, agent correlates migration + slow-query log", tone: "muted" },
    { time: "10:20", text: "Fix PR #207 opened to recreate the index concurrently", tone: "success" },
  ],
  actionItems: [
    { text: "Add a guard preventing index drops without a replacement plan", owner: "TBD" },
    { text: "Alert on p95 query latency for /orders", owner: "TBD" },
  ],
  evidenceBrief: [
    "Migration m-118 dropped the composite index at 09:10",
    "Seq scans on orders begin exactly at 09:41",
    "All 92 timeouts share the default created_at sort",
  ],
};

// ---------------------------------------------------------------------------
// INC-5 — Null deref after cleanup commit (resolved)
// ---------------------------------------------------------------------------

const INC5_POSTMORTEM_MD = `# INC-5 — Profile crashes after settings-cleanup commit

**Service:** users-svc · **Severity:** sev-2 · **Confidence:** 90% · **Date:** 2026-07-12

_Generated by Responder · reviewed by human._

## Summary

A cleanup commit removed the default initialization of \`settings\`, so \`GET /users/:id/profile\` dereferenced \`settings.id\` as null for any user created before the settings feature shipped.

## Timeline (UTC)

- **17:20** — Commit c-771 ("chore: drop legacy settings defaults") deploys
- **17:33** — First null-deref; 31 errors over the evening for legacy accounts
- **17:45** — Responder opens INC-5, isolates the removed default
- **18:05** — Fix PR #198 opened to restore the default settings object

## Root Cause

Commit \`c-771\` deleted the \`settings = settings ?? DEFAULT_SETTINGS\` fallback. Legacy rows store \`settings = null\`, so \`settings.id\` throws.

## Evidence

1. All 31 stack traces terminate at \`profile.service.ts:88\`
2. Every failing user row has \`settings IS NULL\` in the database
3. Errors begin within a minute of the c-771 deploy

## Fix

PR #198 — fix: restore DEFAULT_SETTINGS fallback — **merged**

## Action Items

- [ ] Backfill null settings rows — owner: TBD
- [ ] Make settings non-nullable at the schema level — owner: TBD
`;

const INC5_RCA: RcaResult = {
  rootCause: "Default settings fallback removed in cleanup commit c-771",
  confidence: 0.9,
  suspectCommit: "c-771",
  evidence: [
    "All 31 stack traces terminate at profile.service.ts:88",
    "Every failing user row has settings IS NULL in the database",
    "Errors begin within a minute of the c-771 deploy",
  ],
  proposedPatch: `@@ profile.service.ts:86 @@
+ const settings = row.settings ?? DEFAULT_SETTINGS;
- const settings = row.settings;
  return settings.id;`,
  postmortemMd: INC5_POSTMORTEM_MD,
  service: "users-svc",
  severity: "sev-2",
  prNumber: 198,
  prUrl: "https://github.com/demo-app/users-svc/pull/198",
  prMerged: true,
  title: "Profile crashes after settings-cleanup commit",
  summary:
    "A cleanup commit removed the default initialization of `settings`, so `GET /users/:id/profile` dereferenced `settings.id` as null for any user created before the settings feature shipped.",
  rootCauseSnippet: `// profile.service.ts — c-771
- const settings = row.settings ?? DEFAULT_SETTINGS;
+ const settings = row.settings;
  return settings.id;   // null for legacy rows`,
  fixDescription: "fix: restore DEFAULT_SETTINGS fallback — merged",
  date: "2026-07-12",
  timeline: [
    { time: "17:20", text: 'Commit `c-771` ("chore: drop legacy settings defaults") deploys', tone: "muted" },
    { time: "17:33", text: "First null-deref; 31 errors over the evening for legacy accounts", tone: "danger" },
    { time: "17:45", text: "Responder opens INC-5, isolates the removed default", tone: "muted" },
    { time: "18:05", text: "Fix PR #198 opened to restore the default settings object", tone: "success" },
  ],
  actionItems: [
    { text: "Backfill null settings rows", owner: "TBD" },
    { text: "Make settings non-nullable at the schema level", owner: "TBD" },
  ],
  evidenceBrief: [
    "Cleanup commit c-771 dropped the settings default",
    "All 31 traces end at profile.service.ts:88",
    "Every failing row has settings IS NULL",
  ],
};

/**
 * Build a fresh set of seed incidents. Returns new objects on every call so the
 * mock client can own a mutable copy without leaking state across instances.
 */
export function createSeedIncidents(): Incident[] {
  const inc7: Incident = {
    id: "INC-7",
    title: "TypeError in checkout flow",
    service: "checkout-api",
    status: "investigating",
    severity: "sev-2",
    error: {
      id: "err-7",
      service: "checkout-api",
      message: "TypeError: Cannot read properties of undefined (reading 'email')",
      method: "POST",
      route: "/checkout",
      firstSeen: "2026-07-15T14:02:00Z",
      lastSeen: "2026-07-15T14:21:00Z",
      count: 14,
      fingerprint: "checkout-api:users.service.ts:42:TypeError",
    },
    occurrences: 14,
    firstSeen: "2026-07-15T14:02:00Z",
    updatedAt: minutesAgo(4),
    steps: [
      { index: 0, ts: "2026-07-15T14:06:10Z", type: "thought", content: "Checking the deploy timeline before reading any code — the error started at 14:02." },
      { index: 1, ts: "2026-07-15T14:06:14Z", type: "tool_call", toolName: "get_deploy_history", toolInput: {} },
      { index: 2, ts: "2026-07-15T14:06:16Z", type: "tool_result", toolName: "get_deploy_history", toolResult: "deploy d-482 → sha a3f9c12, 13:58 UTC, 4 min before first error" },
      { index: 3, ts: "2026-07-15T14:06:20Z", type: "tool_call", toolName: "get_logs", toolInput: { service: "checkout-api", window: "30m" } },
      { index: 4, ts: "2026-07-15T14:06:23Z", type: "tool_result", toolName: "get_logs", toolResult: "14 matching errors, none before 14:02 · surrounding INFO lines normal" },
      { index: 5, ts: "2026-07-15T14:06:28Z", type: "tool_call", toolName: "get_diff", toolInput: { sha: "a3f9c12" } },
      { index: 6, ts: "2026-07-15T14:06:31Z", type: "tool_result", toolName: "get_diff", toolResult: '"refactor: simplify user lookup" · src/users/users.service.ts · −6 +2' },
      { index: 7, ts: "2026-07-15T14:06:40Z", type: "thought", content: "The diff removes the `if (!user) throw NotFound` guard. Every stack trace ends at line 42, where `user.email` is read. Confident enough to submit." },
      { index: 8, ts: "2026-07-15T14:06:58Z", type: "rca", rca: INC7_RCA },
    ],
    // INC-7 is still investigating: the RCA is revealed only when the terminal
    // `rca` step arrives over the stream, and no PR is attached until applyFix.
    rca: undefined,
  };

  const inc6: Incident = {
    id: "INC-6",
    title: "Orders query timeout",
    service: "orders-svc",
    status: "resolved",
    severity: "sev-3",
    error: {
      id: "err-6",
      service: "orders-svc",
      message: "QueryTimeoutError: statement timeout after 5000ms",
      method: "GET",
      route: "/orders",
      firstSeen: "2026-07-13T09:41:00Z",
      lastSeen: "2026-07-13T11:40:00Z",
      count: 92,
      fingerprint: "orders-svc:orders.repository.ts:57:QueryTimeoutError",
    },
    occurrences: 92,
    firstSeen: "2026-07-13T09:41:00Z",
    updatedAt: daysAgo(2),
    steps: [
      { index: 0, ts: "2026-07-13T09:52:00Z", type: "thought", content: "Error rate jumped to 92 with no code deploy — checking for a database migration around the onset time." },
      { index: 1, ts: "2026-07-13T09:52:05Z", type: "tool_call", toolName: "get_deploy_history", toolInput: { service: "orders-svc" } },
      { index: 2, ts: "2026-07-13T09:52:07Z", type: "tool_result", toolName: "get_deploy_history", toolResult: "migration m-118 applied 09:10 UTC; no app deploy since 08:00" },
      { index: 3, ts: "2026-07-13T09:52:12Z", type: "tool_call", toolName: "get_slow_queries", toolInput: { service: "orders-svc", window: "3h" } },
      { index: 4, ts: "2026-07-13T09:52:15Z", type: "tool_result", toolName: "get_slow_queries", toolResult: "seq scan on orders (ORDER BY created_at DESC), avg 6.4s, first at 09:41" },
      { index: 5, ts: "2026-07-13T09:52:22Z", type: "tool_call", toolName: "get_diff", toolInput: { sha: "m-118" } },
      { index: 6, ts: "2026-07-13T09:52:24Z", type: "tool_result", toolName: "get_diff", toolResult: "DROP INDEX idx_orders_customer_created" },
      { index: 7, ts: "2026-07-13T09:52:35Z", type: "thought", content: "The dropped index `idx_orders_customer_created` backed the default `/orders` sort. Without it queries fall back to a full scan and hit the 5s timeout." },
      { index: 8, ts: "2026-07-13T09:52:50Z", type: "rca", rca: INC6_RCA },
    ],
    rca: INC6_RCA,
    prNumber: 207,
    prUrl: "https://github.com/demo-app/orders-svc/pull/207",
    prMerged: true,
  };

  const inc5: Incident = {
    id: "INC-5",
    title: "Null deref after cleanup commit",
    service: "users-svc",
    status: "resolved",
    severity: "sev-2",
    error: {
      id: "err-5",
      service: "users-svc",
      message: "TypeError: Cannot read properties of null (reading 'id')",
      method: "GET",
      route: "/users/:id/profile",
      firstSeen: "2026-07-12T17:33:00Z",
      lastSeen: "2026-07-12T22:10:00Z",
      count: 31,
      fingerprint: "users-svc:profile.service.ts:88:TypeError",
    },
    occurrences: 31,
    firstSeen: "2026-07-12T17:33:00Z",
    updatedAt: daysAgo(3),
    steps: [
      { index: 0, ts: "2026-07-12T17:45:00Z", type: "thought", content: "Null dereference on profile reads — checking what shipped just before 17:33." },
      { index: 1, ts: "2026-07-12T17:45:04Z", type: "tool_call", toolName: "get_deploy_history", toolInput: { service: "users-svc" } },
      { index: 2, ts: "2026-07-12T17:45:06Z", type: "tool_result", toolName: "get_deploy_history", toolResult: "commit c-771 deployed 17:20 UTC, 13 min before first error" },
      { index: 3, ts: "2026-07-12T17:45:12Z", type: "tool_call", toolName: "get_diff", toolInput: { sha: "c-771" } },
      { index: 4, ts: "2026-07-12T17:45:14Z", type: "tool_result", toolName: "get_diff", toolResult: '"chore: drop legacy settings defaults" · profile.service.ts · −1 +0' },
      { index: 5, ts: "2026-07-12T17:45:22Z", type: "thought", content: "The commit removed the `settings ?? DEFAULT_SETTINGS` fallback. Legacy rows store `settings = null`, so `settings.id` throws at line 88." },
      { index: 6, ts: "2026-07-12T17:45:38Z", type: "rca", rca: INC5_RCA },
    ],
    rca: INC5_RCA,
    prNumber: 198,
    prUrl: "https://github.com/demo-app/users-svc/pull/198",
    prMerged: true,
  };

  return [inc7, inc6, inc5];
}
